services:
  - type: web
    name: adynex
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_SECRET_KEY
        generateValue: true        # Render generiert automatisch einen sicheren Zufallsstring
      - key: DATABASE_URL
        fromDatabase:
          name: adynex-db
          property: connectionString

databases:
  - name: adynex-db
    databaseName: adynex
    user: adynex
